title: "Megan Kwok"
email: megankwok.code@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is my portfolio website!
baseurl: "/" 
url: "https://m1kwok.github.io/" 
github_username:  m1kwok

sass:
  sass_dir: _sass

icon: /assets/img/icon.jpg
